site_name: geohaye
site_description: A python package demo for geospatial analysis
site_author: 3bdillahiomar
site_url: https://3bdillahiomar.github.io/geohaye
repo_url: https://github.com/3bdillahiomar/geohaye

copyright: "Copyright &copy; 2024 - 2024 Abdillahi Osman Omar"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["examples/csv.ipynb", "examples/vector.ipynb", "examples/raster.ipynb", "examples/ipyleaflet.ipynb", "examples/demo.ipynb", "examples/intro.ipynb", 
          "examples/random.ipynb", 'examples/ipywidgets.ipynb', "examples/ipyleaflet.ipynb", 'python/10_files_and_exceptions.ipynb', 'examples/toolbar.ipynb',
          'examples/foliumap.ipynb']
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/3bdillahiomar/geohaye/issues
    - API Reference:
          - geohaye module: geohaye.md
          - common module: common.md
          - utils module: utils.md
    - Examples:
        - examples/demo.ipynb
        - examples/intro.ipynb
        - examples/csv.ipynb
        - examples/vector.ipynb
        - examples/raster.ipynb
        - examples/ipyleaflet.ipynb
        - examples/ipywidgets.ipynb
        - examples/toolbar.ipynb
    - Python Basics:
          - python/01_getting_started.ipynb
          - python/02_variables_data_types.ipynb
          - python/03_introducing_lists.ipynb
          - python/04_working_with_lists.ipynb
          - python/05_if_statements.ipynb
          - python/06_dictionaries.ipynb
          - python/07_user_input_while_loops.ipynb
          - python/08_functions.ipynb
          - python/09_classes.ipynb
          - python/10_files_and_exceptions.ipynb
    - External Links:
        - GitHub: https://github.com/3bdillahiomar/geohaye
        - LinkedIn: https://www.linkedin.com/in/abdillahi-osman-omar-7b2724173/
        - Email: mailto:abdillahiosmanomar@student.utwente.nl
