site_name: geohaye
site_description: A python package demo for geospatial analysis
site_author: 3bdillahiomar
site_url: https://3bdillahiomar.github.io/geohaye
repo_url: https://github.com/3bdillahiomar/geohaye

copyright: "Copyright &copy; 2024 - 2024 Abdillahi Osman Omar"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: True
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["*ignore.ipynb"]
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/3bdillahiomar/geohaye/issues
    - API Reference:
          - geohaye module: geohaye.md
          - common module: common.md
          - utils module: utils.md
    - Examples:
        - examples/demo.ipynb
        - examples/intro.ipynb
        - examples/random.ipynb
        - examples/csv.ipynb
        - examples/vector.ipynb
        - examples/ipyleaflet.ipynb

    - Python Basics: 

    - About:
        - License: license.md
        - Acknowledgements: acknowledgements.md
        - Release Notes: release_notes.md
        - Code of Conduct: code_of_conduct.md
        - Privacy Policy: privacy_policy.md
        - Terms of Service: terms_of_service.md
    
    - External Links:
        - GitHub:
            icon: fab fa-github
            url: https://github.com/3bdillahiomar/geohaye
        - Twitter:
            icon: fab fa-twitter
            url: https://twitter.com/3bdillahi
        - LinkedIn:
            icon: fab fa-linkedin
            url: https://www.linkedin.com/in/abdillahi-osman-omar-7b2724173/
        - Email: 
            icon: far fa-envelope
            url: mailto:abdillahiosmanomar@student.utwente.nl
            